### PR TITLE
Fix sort_ascend utility function to sort decimals

### LINKED ISSUE #24: Refactor sort_ascend Utility Function to precisely sort decimal numbers
sort_ascend function needs to be refactored by removing int cast of return value and compare the two values and return 1 when a > b or 0 if a == b and -1 if a < b to prevent losing precision in inputs like {1.2, 1.5, 1.3, 1.8, 1.7} won't be sorted correctly as they all evaluates to zeros

### PR DESCRIPTION
**Pull request by mohammedelgammal**
Refactor sort_ascend function to avoid losing precision when sorting decimals. resolves #24

### CODE REVIEW

File: src/DataTomeUtils.h [hunk 1]
```diff
@@ -21,8 +25,8 @@ void swap(TypeOfArray &a, TypeOfArray &b) {
   b = temp;
 }
 
-template <typename T>
-const T &dt_min(const T &a, const T &b) {
+template <typename TypeOfArray>
+const TypeOfArray &dt_min(const TypeOfArray &a, const TypeOfArray &b) {
```
Comment (AlexandreHiroyuki) [inline src/DataTomeUtils.h:29]: Nice change to comply with the standard used on the codebase! I was thinking of writing it myself. Thank you for noticing it.

**Review by AlexandreHiroyuki — APPROVED** [review]
Nice catch! Everything seems fine to me.
